Home13
IgorPrihodko/CoreRepo pull request #15
Opened 2019-06-21 01:34 UTC by IgorPrihodko

2019-06-23 11:11 UTC, SevostyanovGerman requested changes

2019-06-23 11:11 UTC, SevostyanovGerman commented on src/main/java/homework13/task1/MinMax.java
> +        T[] arr = (T[]) stream.sorted(order).toArray();
use min max

2019-06-23 11:11 UTC, SevostyanovGerman commented on src/main/java/homework13/task2/Deserializable.java
> +        Animal[] animals = null;
why here?

2019-06-24 23:46 UTC, IgorPrihodko commented on src/main/java/homework13/task1/MinMax.java
> +        T[] arr = (T[]) stream.sorted(order).toArray();
Done

2019-06-24 23:46 UTC, IgorPrihodko commented on src/main/java/homework13/task2/Deserializable.java
> +        Animal[] animals = null;
fixed

2019-06-29 16:04 UTC, SevostyanovGerman requested changes

2019-06-29 16:04 UTC, SevostyanovGerman commented on src/main/java/homework13/task1/MinMax.java
> +            T max = list.stream().max(order).get();
why u use 2 streams? just use 1 stream object

2019-06-30 16:38 UTC, IgorPrihodko commented on src/main/java/homework13/task1/MinMax.java
> +            T max = list.stream().max(order).get();
fixed

2019-08-27 07:27 UTC, merged